global:
  name: pretrain-language-model
  phase: train
  stage: pretrain-language
  workdir: workdir
  seed: ~
 
dataset:
  train: {
    roots: ['data/language/lang_train.csv'],
    batch_size: 1000
  }
  test: {
    roots: ['data/language/lang_test.csv'],
    batch_size: 1000
  }

training:
  epochs: 80 #迭代次数
  show_iters: 50 #迭代多少次显示一次训练信息
  eval_iters: 6000 #多少次迭代进行一次模型评估
  save_iters: 20 #每隔多少次迭代保存一次模型参数

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [70, 10],
    gamma: 0.1,
  }
dataset_charset_path: data/vision/tibetan_charset.txt

model:
  name: 'modules.model_language.BCNLanguage'
  language: {
    num_layers: 4,
    loss_weight: 1.,
    use_self_attn: False
  }
